### PR TITLE
Delete Symbolic Link

### PR DESCRIPTION
**Pull request by soartec-lab**
this symboliclink is circulating reference.
Is this what you intended?

### CODE REVIEW

**Comment by r7kamura** [comment]
Hmm, when I started to create Chanko v2, certainly I saw https://stackoverflow.com/questions/8507798/rails-3-1-plugin-gem-dummy-test-app-rspec to test a rails plug-in with RSpec. I think this symlink was needed to run rspec in spec/dummy directory, but I'm no longer sure if it is still useful.

It would be okay to remove this symlink because `bundle exec rake` can work fine without it.

**Comment by sanemat** [comment]
ping @taiki45 @eagletmt

**Comment by sanemat** [comment]
I can't use bootsnap gem, because of this issue 🐰

**Comment by soartec-lab** [comment]
The reason I noticed this phenomenon is when I entered the Zip command on DebianOS.
```
$ cat /etc/debian_version
8.9
$ git clone https://github.com/cookpad/chanko.git
$ zip chanko -r chanko
zip warning: name not matched: chanko/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec/dummy/spec
```

**Comment by eagletmt** [comment]
I found all examples are doubly executed.
So I'll merge this regardless of the packaging issue. Thanks.

**Comment by soartec-lab** [comment]
I gained a lot of knowledge on this issue.
Thank you so match.

**Comment by eagletmt** [comment]
Released v2.1.1 https://rubygems.org/gems/chanko/versions/2.1.1

**Pull request merged**
