### PR TITLE
Fix a deprecation warning in Rails 5

### PR DESCRIPTION
**Pull request by sachin21**
If rails version using chanko is rails 5, use prepend_before_action. else use the prepend_before_filter.

### CODE REVIEW

**Comment by sachin21** [comment]
@eagletmt @r7kamura How about this?

**Comment by eagletmt** [comment]
Looks good.
How about dropping support for Rails 3.x and always use `prepend_before_action` ? `prepend_before_action` is available in Rails >= 4.0, IIRC.

/cc @cookpad/dev-infra

**Comment by moro** [comment]
Looks good for me, too.

And I also agree with @eagletmt suggestion; dropping Rails 3.x support.

**Comment by r7kamura** [comment]
LGTM, and +1 for the supported Rails version change 👍

**Comment by sachin21** [comment]
Thank you for reviewing. I changed to following.

### Changes
- Replace `prepend_before_filter` with `prepend_before_action`.
- Drop support Rails 3.x and update `README.md`.

@eagletmt @r7kamura @moro

**Comment by r7kamura** [comment]
@sachin21 Great 👍 
We also need to change the runtime dependency version in chanko.gemspec

**Comment by sachin21** [comment]
Oops! I'll fix right now.

**Comment by sachin21** [comment]
@r7kamura Thank you! I fixed it and CI looks like all is well.

**Comment by sachin21** [comment]
Thank you so much!

**Pull request merged**
